scripts

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -5,18 +5,16 @@ if [ -f ~/.zshrc ]; then
     source ~/.zshrc
 fi
 
-NPM_GLOBAL_DIR="/usr"
-npm config set prefix "$NPM_GLOBAL_DIR"
-export PATH="$NPM_GLOBAL_DIR/bin:$PATH"
-
-# Optional: Source your zshrc if you need your zsh configuration
-# source ~/.zshrc
-
 # Ejecutar el build
 echo "Building the project..."
 
-if ! ./generate_doc.sh; then
+if ! ./scripts/generate_doc.sh; then
     echo "Build failed generating docs."
+    exit 1
+fi
+
+if ! ./scripts/generate_gql.sh; then
+    echo "Build failed generating gql."
     exit 1
 fi
 
